export type CalculatorCategory =
  | 'Finanza'
  | 'Fisco'
  | 'Matematica'
  | 'Salute'
  | 'Scuola'
  | 'Utilita'

export interface CalculatorCatalogEntry {
  id: string
  title: string
  category: CalculatorCategory
  popularity: 'Molto Alto' | 'Alto' | 'Medio'
  description: string
  tags: string[]
}

export const CALCULATOR_CATALOG: CalculatorCatalogEntry[] = [
  {
    id: 'percentuali',
    title: 'Calcolo Percentuali',
    category: 'Matematica',
    popularity: 'Molto Alto',
    description: 'Percentuali dirette/inverse, variazione percentuale e calcoli concatenati.',
    tags: ['percentuale', 'sconto', 'proporzioni', 'matematica', 'variazione'],
  },
  {
    id: 'giorni-tra-date',
    title: 'Giorni tra Date',
    category: 'Utilita',
    popularity: 'Alto',
    description: 'Differenza tra date con modalita calendario o giorni lavorativi.',
    tags: ['giorni', 'date', 'scadenza', 'tempo', 'giorni lavorativi'],
  },
  {
    id: 'scorporo-iva',
    title: 'Scorporo IVA',
    category: 'Fisco',
    popularity: 'Molto Alto',
    description: 'Calcola imponibile e IVA da importi lordi o netti.',
    tags: ['iva', 'fisco', 'fattura', 'imponibile'],
  },
  {
    id: 'calcolo-imu',
    title: 'Calcolo IMU',
    category: 'Fisco',
    popularity: 'Molto Alto',
    description: 'Stima IMU annua con rendita catastale, aliquota e quote di possesso.',
    tags: ['imu', 'casa', 'tasse', 'rendita catastale', 'fisco'],
  },
  {
    id: 'codice-fiscale',
    title: 'Codice Fiscale',
    category: 'Fisco',
    popularity: 'Molto Alto',
    description: 'Genera e valida codice fiscale italiano.',
    tags: ['codice fiscale', 'anagrafica', 'fisco'],
  },
  {
    id: 'rata-mutuo',
    title: 'Rata Mutuo',
    category: 'Finanza',
    popularity: 'Molto Alto',
    description: 'Rata mutuo con extra versamenti, fee e stima risparmio interessi.',
    tags: ['mutuo', 'rata', 'casa', 'interessi', 'estinzione anticipata'],
  },
  {
    id: 'busta-paga-netta',
    title: 'Busta Paga Netta',
    category: 'Finanza',
    popularity: 'Molto Alto',
    description: 'Simula stipendio netto mensile da RAL, contributi e imposte.',
    tags: ['busta paga', 'stipendio netto', 'ral', 'irpef', 'contributi'],
  },
  {
    id: 'quote-dashboard',
    title: 'Quote Dashboard',
    category: 'Finanza',
    popularity: 'Medio',
    description: 'Motore pricing con validazione speculare e CMP zero-drift.',
    tags: ['quote', 'pricing', 'validation', 'cmp', 'risk factor'],
  },
  {
    id: 'rata-prestito',
    title: 'Rata Prestito',
    category: 'Finanza',
    popularity: 'Molto Alto',
    description: 'Rata mensile e costo totale del prestito.',
    tags: ['prestito', 'rata', 'finanziamento', 'interessi'],
  },
  {
    id: 'interesse-composto',
    title: 'Interesse Composto',
    category: 'Finanza',
    popularity: 'Alto',
    description: 'Crescita del capitale con capitalizzazione periodica.',
    tags: ['interessi composti', 'investimento', 'capitale'],
  },
  {
    id: 'sconto-percentuale',
    title: 'Sconto Percentuale',
    category: 'Finanza',
    popularity: 'Alto',
    description: 'Prezzo finale e risparmio totale su uno sconto.',
    tags: ['sconto', 'prezzo', 'shopping'],
  },
  {
    id: 'aumento-percentuale',
    title: 'Aumento Percentuale',
    category: 'Finanza',
    popularity: 'Alto',
    description: 'Aumento assoluto e nuovo importo finale.',
    tags: ['aumento', 'incremento', 'percentuale'],
  },
  {
    id: 'interesse-semplice',
    title: 'Interesse Semplice',
    category: 'Finanza',
    popularity: 'Medio',
    description: 'Interessi lineari su capitale, tasso e durata.',
    tags: ['interessi', 'investimento', 'prestito'],
  },
  {
    id: 'indice-massa-corporea',
    title: 'Indice Massa Corporea (BMI)',
    category: 'Salute',
    popularity: 'Molto Alto',
    description: 'BMI multi-unita, BMI Prime e range peso normopeso.',
    tags: ['bmi', 'salute', 'peso', 'altezza'],
  },
  {
    id: 'fabbisogno-calorico',
    title: 'Fabbisogno Calorico',
    category: 'Salute',
    popularity: 'Molto Alto',
    description: 'BMR/TDEE, target obiettivo e macronutrienti con unita metriche o imperiali.',
    tags: ['calorie', 'metabolismo', 'tdee', 'salute'],
  },
  {
    id: 'metabolismo-basale',
    title: 'Metabolismo Basale (BMR)',
    category: 'Salute',
    popularity: 'Molto Alto',
    description: "Stima del metabolismo basale con l'equazione di Mifflin-St Jeor (1990).",
    tags: ['metabolismo', 'bmr', 'calorie', 'salute'],
  },
  {
    id: 'teorema-pitagora',
    title: 'Teorema di Pitagora',
    category: 'Matematica',
    popularity: 'Alto',
    description: "Calcola l'ipotenusa di un triangolo rettangolo dai due cateti.",
    tags: ['pitagora', 'ipotenusa', 'cateti', 'geometria', 'matematica'],
  },
  {
    id: 'regola-del-tre',
    title: 'Regola del Tre',
    category: 'Matematica',
    popularity: 'Alto',
    description: 'Risolvi una proporzione a : b = c : x.',
    tags: ['proporzioni', 'regola del tre', 'incognita', 'matematica'],
  },
  {
    id: 'area-trapezio',
    title: 'Area Trapezio',
    category: 'Matematica',
    popularity: 'Medio',
    description: 'Area del trapezio da base maggiore, base minore e altezza.',
    tags: ['trapezio', 'area', 'geometria', 'basi'],
  },
  {
    id: 'volume-cono',
    title: 'Volume Cono',
    category: 'Matematica',
    popularity: 'Medio',
    description: 'Volume del cono da raggio e altezza.',
    tags: ['cono', 'volume', 'geometria'],
  },
  {
    id: 'media-voti',
    title: 'Media Voti Ponderata',
    category: 'Scuola',
    popularity: 'Alto',
    description: 'Media pesata con voti e crediti.',
    tags: ['media', 'voti', 'universita', 'crediti'],
  },
  {
    id: 'cifrario-enigma',
    title: 'Cifrario Enigma',
    category: 'Scuola',
    popularity: 'Medio',
    description: 'Simula Enigma con rotori, reflector e plugboard.',
    tags: ['enigma', 'cifrario', 'crittografia', 'rotori', 'plugboard'],
  },
  {
    id: 'area-rettangolo',
    title: 'Area Rettangolo',
    category: 'Matematica',
    popularity: 'Medio',
    description: 'Area, perimetro e conversioni complete delle unita di superficie.',
    tags: ['area', 'rettangolo', 'geometria'],
  },
  {
    id: 'area-cerchio',
    title: 'Area Cerchio',
    category: 'Matematica',
    popularity: 'Medio',
    description: 'Area, diametro, circonferenza e conversioni complete delle unita di superficie.',
    tags: ['area', 'cerchio', 'geometria'],
  },
  {
    id: 'conversione-temperatura',
    title: 'Conversione Temperatura',
    category: 'Utilita',
    popularity: 'Medio',
    description: 'Converti tra Celsius, Fahrenheit, Kelvin e Rankine.',
    tags: ['temperatura', 'conversione', 'unita'],
  },
  {
    id: 'convertitore-unita-lunghezza',
    title: 'Convertitore Lunghezze',
    category: 'Utilita',
    popularity: 'Alto',
    description: 'Converte da qualsiasi unita in metriche, imperiali e nautiche.',
    tags: ['conversione', 'lunghezza', 'metri', 'miglia', 'piedi'],
  },
  {
    id: 'numeri-casuali',
    title: 'Numeri Casuali',
    category: 'Matematica',
    popularity: 'Alto',
    description: 'Generatore interi/decimali con seed deterministico, ordinamento e controllo duplicati.',
    tags: ['numeri casuali', 'estrazione', 'random', 'matematica'],
  },
  {
    id: 'calcolo-eta',
    title: 'Calcolo Età',
    category: 'Utilita',
    popularity: 'Molto Alto',
    description: 'Calcola età precisa in anni, mesi e giorni.',
    tags: ['età', 'nascita', 'anni', 'date'],
  },
  {
    id: 'calcolo-mancia',
    title: 'Calcolo Mancia',
    category: 'Utilita',
    popularity: 'Alto',
    description: 'Mancia con servizio, split conto e arrotondamenti avanzati per persona.',
    tags: ['mancia', 'ristorante', 'conto'],
  },
  {
    id: 'consumo-carburante',
    title: 'Consumo Carburante',
    category: 'Utilita',
    popularity: 'Medio',
    description: 'Calcola consumi multi-unita, MPG e costo percorso.',
    tags: ['carburante', 'auto', 'consumi'],
  },
  // Nuovi calcolatori aggiunti
  {
    id: 'media-ponderata',
    title: 'Media Ponderata',
    category: 'Matematica',
    popularity: 'Medio',
    description: 'Calcola media ponderata con pesi personalizzati.',
    tags: ['media', 'ponderata', 'voti', 'pesi'],
  },
  {
    id: 'volume-parallelepipedo',
    title: 'Volume Parallelepipedo',
    category: 'Matematica',
    popularity: 'Medio',
    description: 'Calcola volume e area superficiale di un parallelepipedo.',
    tags: ['volume', 'parallelepipedo', 'geometria', 'area'],
  },
  {
    id: 'volume-sfera',
    title: 'Volume Sfera',
    category: 'Matematica',
    popularity: 'Medio',
    description: 'Calcola volume e area superficiale di una sfera.',
    tags: ['volume', 'sfera', 'geometria', 'raggio'],
  },
  {
    id: 'volume-cilindro',
    title: 'Volume Cilindro',
    category: 'Matematica',
    popularity: 'Medio',
    description: 'Calcola volume, area laterale e totale di un cilindro.',
    tags: ['volume', 'cilindro', 'geometria', 'raggio'],
  },
  {
    id: 'rata-leasing',
    title: 'Rata Leasing',
    category: 'Finanza',
    popularity: 'Alto',
    description: 'Calcola rata leasing con anticipo e valore residuo.',
    tags: ['leasing', 'rata', 'finanziamento', 'auto'],
  },
  {
    id: 'tan-taeg',
    title: 'Calcolo TAN e TAEG',
    category: 'Finanza',
    popularity: 'Molto Alto',
    description: 'Calcola TAN e TAEG di un finanziamento.',
    tags: ['tan', 'taeg', 'tasso', 'finanziamento', 'interessi'],
  },
  {
    id: 'bollo-auto',
    title: 'Bollo Auto',
    category: 'Fisco',
    popularity: 'Molto Alto',
    description: 'Calcola bollo auto in base a potenza, regione e classe ambientale.',
    tags: ['bollo', 'auto', 'tassa', 'regione', 'Euro'],
  },
  {
    id: 'calcolo-tfr',
    title: 'Calcolo TFR',
    category: 'Fisco',
    popularity: 'Alto',
    description: 'Calcola TFR (Trattamento di Fine Rapporto) con rivalutazione.',
    tags: ['tfr', 'liquidazione', 'dipendente', 'inflazione'],
  },
  {
    id: 'rivalutazione-monetaria',
    title: 'Rivalutazione Monetaria',
    category: 'Finanza',
    popularity: 'Medio',
    description: 'Rivaluta un importo in base allinflazione nel tempo.',
    tags: ['rivalutazione', 'inflazione', 'moneta', 'indice'],
  },
  {
    id: 'stima-pensione',
    title: 'Stima Pensione',
    category: 'Finanza',
    popularity: 'Alto',
    description: 'Stima pensione pubblica in base a stipendo e contributi.',
    tags: ['pensione', 'stima', 'contributi', 'età'],
  },
  {
    id: 'area-triangolo',
    title: 'Area Triangolo',
    category: 'Matematica',
    popularity: 'Medio',
    description: 'Calcola area e perimetro di un triangolo.',
    tags: ['area', 'triangolo', 'geometria', 'base', 'altezza'],
  },
]

export const CALCULATOR_CATEGORIES: CalculatorCategory[] = [
  'Finanza',
  'Fisco',
  'Matematica',
  'Salute',
  'Scuola',
  'Utilita',
]
